apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.compoundInterest.service.name }}
spec:
  type: {{ .Values.compoundInterest.service.type }}
  selector:
    app: {{ .Values.compoundInterest.labelapp }}
  ports:
    - protocol: TCP
      port: {{ .Values.compoundInterest.service.port }}
      targetPort: {{ .Values.compoundInterest.service.port }}
      nodePort: {{ .Values.compoundInterest.service.nodePort }}