
# templates/mongo-express.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: {{ .Values.mongoExpress.labelapp }}
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongoExpress.labelapp }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoExpress.labelapp }}
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.mongoExpress.image }}
        ports:
        - containerPort: {{ .Values.mongoExpress.containerPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
           secretKeyRef:
            name: {{ .Values.mongoSecret.name }}
            key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
           secretKeyRef:
            name: {{ .Values.mongoSecret.name }}
            key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
           configMapKeyRef:
            name: {{ .Values.mongoConfig.name }}
            key: mongo-url

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.mongoExpress.service.name }}
# spec:
#   selector:
#     app: {{ .Values.mongoExpress.labelapp }}
#   type: {{ .Values.mongoExpress.service.type }}
#   ports:
#     - protocol: TCP
#       port: {{ .Values.mongoExpress.service.port }}
#       targetPort: {{ .Values.mongoExpress.service.port }}
#       nodePort: {{ .Values.mongoExpress.service.nodePort }}
