apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  selector:
    app: {{ .Values.mongodb.labelapp }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}