# templates/mongo-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecret.name }}
type: {{ .Values.mongoSecret.type }}
data:
  mongo-user: {{ .Values.mongoSecret.data.mongouser }}
  mongo-password: {{ .Values.mongoSecret.data.mongopassword }}
