
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongoConfig.name }}
data:
  mongo-url: {{ .Values.mongoConfig.data.mongourl }}
  mongo-key: {{ .Values.mongoConfig.data.mongokey }}
  # debug: {{ .Values.mongoConfig.data.debug }}
