name: Merge Feature to master

on:
  workflow_run:
    workflows: ["Test K8 and Helm"]
    types:
      - completed
      
jobs:
  merge-main:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@master

    - name: Merge to master
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: feature
        target_branch: master
        github_token: ${{ secrets.GIT_TOKEN }}
